language: python
python:
 - 2.7
 - 3.4
sudo: false
env:
  - DISPLAY=:0.0
install:
  - pip install -e .[test]
script:
  - export APPLITOOLS_BATCH_ID=`uuidgen -t`
  - echo $APPLITOOLS_BATCH_ID
  - python applitools_sauce_test.py
  - pytest test/server_results_text.py
